### ISSUE TITLE
Error when permuting plots within blocks

### ISSUE THREAD

**Issue by brendanf** [gavinsimpson/permute#15]
```
# using fresh install of permute 0.8-4
blk <- gl(2,4)
plt <- gl(4,2)
ctrl <- how(block=blk,
            plots=Plots(strata=plt, type='free'))
ctrl <- check(8, ctrl)$control
shuffle(8, ctrl)
# Error in shuffleStrata(Pstrata, type = typeP, mirror = plotCTRL$mirror,  : 
  replacement has length zero
```

**Comment by gavinsimpson** [comment]
This has been fixed in the development version (>= 0.8-5):

```r
> library(permute)
> packageVersion("permute")
[1] ‘0.8.5’
> # using fresh install of permute 0.8-4
> blk <- gl(2,4)
> plt <- gl(4,2)
> ctrl <- how(block=blk,
+             plots=Plots(strata=plt, type='free'))
> ctrl <- check(8, ctrl)$control
'nperm' >= set of all permutations: complete enumeration.
Set of permutations < 'minperm'. Generating entire set.
> shuffle(8, ctrl)
[1] 1 2 3 4 8 7 5 6
```

I was planning to get a new release out to CRAN at the start of the year but I've been unwell and it hasn't happened yet. If you can build from source then just grab the source code from here and build and install permute. If you are on Windows, there's a pre-built binary at the Appveyor CI service I use to test Windows versions of the the package. You can grab the zip from the build artefacts:

https://ci.appveyor.com/project/gavinsimpson/permute/branch/master/artifacts
